- README.md
- src/main.rs
> fix: Check that jj is installed on start

- src/main.rs
- src/ui/command_log.rs
- src/ui/files.rs
- src/ui/log.rs
- src/ui/mod.rs
Fixed https://github.com/Cretezy/lazyjj/issues/11
> fix: Make q/esc close popups

- src/commander/mod.rs
- src/ui/command_log.rs
Fixed https://github.com/Cretezy/lazyjj/issues/17
> feat: Add command duration

- README.md
- src/app.rs
- src/commander/branches.rs
- src/commander/files.rs
- src/commander/jj.rs
- src/commander/log.rs
- src/ui/branches.rs
- src/ui/log.rs
- src/ui/mod.rs
Fixes https://github.com/Cretezy/lazyjj/issues/27
- Add `Enter` to view branch in log
- Add `n` to create new from branch
- Add `N` to create new and describe from branch
- Add `e` to edit branch
Todo:
> feat: More branch actions

- src/app.rs
- src/main.rs
- src/ui/branch_set_popup.rs
- src/ui/branches_tab.rs
- src/ui/command_log_tab.rs
- src/ui/files_tab.rs
- src/ui/help_popup.rs
- src/ui/log_tab.rs
- src/ui/message_popup.rs
- src/ui/mod.rs
- src/ui/styles.rs
Fixes https://github.com/Cretezy/lazyjj/issues/13. Refactors how popups are handled
To do:
- Still a few left
> feat: Add help menu

- .github/workflows/publish.yml
- .github/workflows/test.yml
- Cargo.lock
I also added `--locked` flag to CI for avoiding this in the future :)
> chore: update Cargo.lock

- Cargo.lock
- src/commander/jj.rs
- src/ui/log_tab.rs
Fixes https://github.com/Cretezy/lazyjj/issues/47
> feat: Push selected change

- src/app.rs
- src/commander/branches.rs
- src/commander/log.rs
- src/main.rs
- src/ui/branch_set_popup.rs
- src/ui/branches_tab.rs
- src/ui/command_log_tab.rs
- src/ui/files_tab.rs
- src/ui/help_popup.rs
- src/ui/log_tab.rs
> refactor: remove unstable let_chains feature

- .gitignore
- Cargo.lock
- Cargo.toml
- README.md
- src/app.rs
- src/commander/branches.rs
- src/commander/files.rs
- src/commander/jj.rs
- src/commander/log.rs
- src/commander/mod.rs
- src/main.rs
- src/ui/branches_tab.rs
- src/ui/command_log_tab.rs
- src/ui/files_tab.rs
- src/ui/log_tab.rs
- src/ui/mod.rs
Added `LAZYJJ_LOG=1` and `LAZYJJ_TRACE=1`. Info in README.
> Add logging/tracing, make tabs lazy loaded, add frame time in top right corner

- Cargo.lock
- Cargo.toml
> fix: update tui dependencies

- src/main.rs
Previous attempt to fix terminal was #51
> fix: do not panic on draw errors

- src/ui/bookmark_set_popup.rs
> fix: close popup on `esc` when creating branch

- src/commander/bookmarks.rs
- src/commander/files.rs
- src/commander/jj.rs
- src/commander/log.rs
- src/commander/mod.rs
- src/ui/command_log_tab.rs
fix #50 
- use arc\<mutex\> for storing command history
> fix: check if change is deleted

- src/commander/jj.rs
- src/ui/log_tab.rs
Currently only already pushed bookmarks can be updated.  Add support for pushing new ones as well using Ctrl-p/P
> Add support for pushing new bookmarks

- src/ui/log_tab.rs
> fix: do not refresh when popup is opened

- README.md
- src/app.rs
- src/commander/bookmarks.rs
- src/commander/files.rs
- src/commander/log.rs
- src/commander/mod.rs
- src/env.rs
- src/ui/bookmarks_tab.rs
- src/ui/files_tab.rs
- src/ui/log_tab.rs
Fixes https://github.com/Cretezy/lazyjj/issues/36
> feat: Add support for ui.diff.tool

- Cargo.lock
- Cargo.toml
- README.md
- docs/keybindings.md
- src/commander/bookmarks.rs
- src/commander/files.rs
- src/commander/log.rs
- src/commander/mod.rs
- src/env.rs
- src/keybinds/config.rs
- src/keybinds/keybinds_store.rs
- src/keybinds/log_tab.rs
- src/keybinds/mod.rs
- src/main.rs
- src/ui/bookmarks_tab.rs
- src/ui/command_log_tab.rs
- src/ui/files_tab.rs
- src/ui/log_tab.rs
- src/ui/utils.rs
Initial implementation, currently only shortcuts for log tab can be configured
Ref #69
> feat: configure keybinds

- .github/workflows/publish.yml
- .github/workflows/test.yml
Hopefully fixes ARM macOS tests
> chore: Upgrade CI

- src/app.rs
- src/ui/bookmarks_tab.rs
- src/ui/command_log_tab.rs
- src/ui/files_tab.rs
- src/ui/log_tab.rs
- src/ui/mod.rs
Looking for testers for this. Seems to be working as expected for me
> feat: Only fetch latest head on switch, handle terminal focus

- src/commander/bookmarks.rs
- src/commander/jj.rs
- src/ui/bookmark_set_popup.rs
Sorts by commit time of the bookmark's target.
Fixes https://github.com/Cretezy/lazyjj/issues/103
> feat: Sort bookmarks in bookmark popup/list

- README.md
- src/commander/bookmarks.rs
- src/commander/files.rs
- src/commander/log.rs
- src/commander/mod.rs
- src/env.rs
- src/ui/bookmarks_tab.rs
- src/ui/files_tab.rs
- src/ui/log_tab.rs
Fixes https://github.com/Cretezy/lazyjj/issues/36#issuecomment-2692892174
> feat: Add `lazyjj.diff-tool` option to customize diff-tool from `ui.diff.tool`

- src/keybinds/mod.rs
see https://rust-lang.github.io/rust-clippy/master/index.html#double_ended_iterator_last
> fix: last -> next_back

- .github/workflows/test.yml
> fix(ci): do not fail test on macos

- src/ui/log_tab.rs
> chore: make clippy happy

- Cargo.toml
- src/app.rs
- src/commander/files.rs
- src/commander/jj.rs
- src/commander/log.rs
- src/env.rs
- src/keybinds/log_tab.rs
- src/main.rs
- src/ui/bookmark_set_popup.rs
- src/ui/bookmarks_tab.rs
- src/ui/command_log_tab.rs
- src/ui/command_popup.rs
- src/ui/files_tab.rs
- src/ui/help_popup.rs
- src/ui/log_tab.rs
- src/ui/message_popup.rs
- src/ui/mod.rs
> chore: update edition to 2024

- src/commander/log.rs
- src/ui/log_tab.rs
Make it possible to click on a change in the log view to select it. This is faster than scrolling.
> feat: Select change via mouse click
