README.md
src/app.rs
src/commander/branches.rs
src/commander/files.rs
src/commander/jj.rs
src/commander/log.rs
src/commander/mod.rs
src/commander/snapshots/lazyjj__commander__branches__tests__get_branch_show.snap
src/env.rs
src/main.rs
src/ui/branch_set_popup.rs
src/ui/branches.rs
src/ui/command_log.rs
src/ui/files.rs
src/ui/log.rs
src/ui/mod.rs

Fixed https://github.com/Cretezy/lazyjj/issues/3
Status: Working, could be better. Waiting for 0.18 (~1 week) for release due to [branch templating](https://github.com/martinvonz/jj/commit/12b873e1eff64ed3bca9bf4d1a7547c7c0c98bfd) support.
Out of scope:
- Push branch
Notes:
- Currently, conflicted branches are shown in the list, but the list does not show the list of commits the branch points to. This is due to the way lazyjj's branch list templating is currently implemented, and could be fixed to allow selecting each of the commits.

feat: Branches tab

---

src/commander/log.rs

Initial fix for https://github.com/Cretezy/lazyjj/issues/29. Doesn't highlight perfectly, but functional.

fix: Branches with newlines break log

---

src/ui/branch_set_popup.rs

Matches behavior of `jj git push -c`

fix: Make generated branch names 12 characters long

---

.github/workflows/publish.yml
.github/workflows/test.yml

GitHub deprecated macos-11, migrating to macos-13

chore: Fix macOS CI

---

.github/workflows/winget.yml

I put this together and have run it as a script and it works.
1. It needs a PAT with access to public repos ([ref](https://github.com/microsoft/winget-create/blob/main/README.md#github-personal-access-token-classic-permissions)
1. In the workflow I named this `PAT_WINGET` but rename it to whatever you want.
1. I *think* it wants you to have a fork of [winget-pkgs](https://github.com/microsoft/winget-pkgs) - but I couldn't find a supporting doc, but read it in a comment somewhere.  I already had it forked, so maybe try it without first to see if it needs it or not.
When run, it will open a PR on the winget-pkgs repo for the version update of `Cretezy.lazyjj` in your name.  Since we have had problems with this passing, you may need to watch the open PRs to make sure the eventually pass.

Adding workflow for winget publishing

---

src/commander/jj.rs

This is a small bug fix. Currently `P` will fail.

Don’t use -r with --all for git push

---

src/commander/log.rs

fix: search latest head by change id instead of commit id

---

src/main.rs

The UI doesn't change based on MouseMoved events, and a redraw is pretty expensive, causing the whole app to freeze for some time whenever the mouse is moved on top of it. We can fix that by simply ignoring MouseMoved events.
Fixes #82

Don't redraw on MouseMoved events

---

README.md
src/env.rs
src/ui/bookmarks_tab.rs
src/ui/command_log_tab.rs
src/ui/files_tab.rs
src/ui/help_popup.rs
src/ui/log_tab.rs

I use a vertical monitor so the default horizontal layout is pretty much unusable for me.
This PR adds two config options:
- `lazyjj.layout` which is either `"horizontal"` (default) or `"vertical"`
- `lazyjj.layout-percent` which should be an integer between 0 and 100 (default 50) which is the size of the main tab as a percentage of the screen
This PR also renames the "left" pane to the "main" pane and the "right" pane to the "details" pane.

Add vertical layout

---

src/app.rs
src/main.rs
src/ui/bookmarks_tab.rs
src/ui/command_popup.rs
src/ui/log_tab.rs
src/ui/message_popup.rs
src/ui/mod.rs

- Added a new field to MessagePopup called `text_align` for text alignment which defaults to Center.
- Updated all references to pass None for message popup.
- Added a new popup called `CommandPopup` which is activated when `:` is pressed from any of the tabs.
- The popup provides a TextArea which allows the user to run a jj command
e.g. when `help` is typed, it will run `jj help`
- Enter to confirm and execute the command
- Esc to close the popup
- Commands with output or an error message will show it in a message popup using the left align
- Commands without output close the textarea and return to the view before running command popup (if they fail, they still show the error message) 
- New action to refresh the current tab which is called after running a command 
Open to design …

feat: Command popup

---

src/ui/log_tab.rs

tui_confirm_dialog defaults to making the message text white, which causes it to be invisible in light terminal themes. Workaround it by explicitly settings the foregroud color to its default value.

Fix confirmation dialog text being invisible on light themes

---

src/commander/jj.rs
src/ui/log_tab.rs

For now, this just squashes everything into the selected commit, which is quite a large hammer, but still useful when working on in a mega merge workflow and pushing down a whole set of changes into a new parent.
It would be useful to add a way to do an interactive squashing, but the current support to run jj command only allows non-interactive ones, so we'll have to add that later.

log tab: bind `s` to squash changes from @ into the selected change

---

src/app.rs
src/ui/bookmarks_tab.rs
src/ui/command_log_tab.rs
src/ui/files_tab.rs
src/ui/log_tab.rs
src/ui/mod.rs

This add the vim keys 'h' and 'l' shortcuts for going forward and backwards one tab - I sorely missed this, and it's more in line with tools like lazydocker this way. Picking a commit with Return is fine, but hitting 1 to 'go back' is awkward, IMHO. 
Also, since I'm not a rust programmer, take this commit more as a suggestion and feel free to change anything.
edit: Oh, and this obviously removes 'h' as the help key, but since '?' is there already, this should be fine, since this is an operation that's not common, except during the first few times running the program.

Add h/l keys for prev/next tab

---

src/commander/bookmarks.rs
src/commander/files.rs
src/commander/log.rs
src/ui/bookmarks_tab.rs
src/ui/files_tab.rs
src/ui/log_tab.rs

More performance optimizations

feat: Don't snapshot working copy when getting diff

---

Cargo.lock
Cargo.toml
src/app.rs
src/keybinds/keybinds_store.rs
src/keybinds/log_tab.rs
src/keybinds/mod.rs
src/main.rs
src/ui/bookmark_set_popup.rs
src/ui/bookmarks_tab.rs
src/ui/command_log_tab.rs
src/ui/command_popup.rs
src/ui/details_panel.rs
src/ui/files_tab.rs
src/ui/help_popup.rs
src/ui/log_tab.rs
src/ui/message_popup.rs
src/ui/mod.rs

Update dependencies. This includes a fix for a breaking change in tui_confirm_dialog 0.2.6 and removes crossterm as a direct dependency, using the re-export from ratatui instead, so that crossterm won't needlessly show up in `cargo outdated` output. That also prevents accidental upgrade attempts that would end up with incompatible versions.

chore: Update dependencies

---

.github/workflows/test.yml

According to
https://github.com/cargo-bins/cargo-binstall/issues/2045#issuecomment-2678217920 one should export the GITHUB_TOKEN as an environment variable for more reliable cargo-binstall execution in GitHub Actions. cargo-binstall also does this itself. For example: https://github.com/cargo-bins/cargo-binstall/blob/a803508dbf9c51e6ba0a3a68aa5bcb3b8fc6f4e2/.github/workflows/ci.yml#L85C1-L85C92

fix: Workaround timeouts in Mac CI tests

---

Cargo.toml

On my system this will reduce the release build binary to about half size.

build: Optimize release build for size

---

src/ui/log_tab.rs

Most of the popups are handled in update()
but not describe.

fix: Update selection after command "describe" (fix #135)

---

src/ui/log_tab.rs

PR 143 introduced a bug that would move the selection to revision @ after a describe command.

fix: Changing description should not move selection

---

Cargo.lock
Cargo.toml
src/commander/mod.rs
src/main.rs

Check that jj is at least version 0.22, which introduced the "bookmark" command.
Fix #138

feat: Check jj version at startup (fix #138)

---

README.md

Recommend the use of `--locked` when installing `lazyjj` with `cargo install`
Related to #153

doc: Recommend `--locked` for cargo install

---

src/app.rs
src/commander/bookmarks.rs
src/commander/log.rs
src/commander/mod.rs
src/main.rs
src/ui/bookmarks_tab.rs
src/ui/files_tab.rs
src/ui/help_popup.rs
src/ui/log_tab.rs
src/ui/styles.rs

--config-toml has been removed so we need to use --config instead, which has a bit stricter format requirements. No leading/trailing new lines, and no spaces around the equal sign.
It can also only take a single option at a time, so we need to change jj_config_toml from a String to a Vec<String>.
And for obslog/evolog, the template format has changed, so we need to
update that as well.

fix: jj 0.33.0 and Rust 1.89.0 compatibility
